// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/tools/add_memory.ts";
import * as module_3 from "../../agent/tools/execute_forget.ts";
import * as module_4 from "../../agent/tools/get_profile.ts";
import * as module_5 from "../../agent/tools/preview_forget.ts";
import * as module_6 from "../../agent/tools/search_memories.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "tools/add_memory.ts": module_2,
                  "tools/execute_forget.ts": module_3,
                  "tools/get_profile.ts": module_4,
                  "tools/preview_forget.ts": module_5,
                  "tools/search_memories.ts": module_6
                })
            })
    })
});

export default moduleMap;
