// Generated by eve. Do not edit by hand.
import { POST } from "./workflows.mjs";
import "../../dev-runtime/snapshots/mreaifzn-bf2ca7b2-394c-43ad-810a-0a3df00cd689/source/.eve/compile/compiled-artifacts-workflow-world.mjs";
import { getWorld as __eveGetWorkflowWorld } from "/Users/mahmoudaidaros/Projects/sphackathon/node_modules/eve/dist/src/internal/workflow/runtime.js";

try {
  const __eveWorkflowWorld = await __eveGetWorkflowWorld();
  if (typeof __eveWorkflowWorld?.registerHandler === "function") {
    __eveWorkflowWorld.registerHandler("__eve73706861636b6174686f6e_wkf_workflow_", POST);
  }
} catch (err) {
  console.warn("[eve] Failed to register direct workflow queue handlers:", err);
}

export default async ({ req }) => {
  return await POST(req);
};
